<?php

/**
 * @file
 * Contains ys_toolbar.module functions.
 */

/**
 * Implements hook_toolbar_alter().
 */
function ys_toolbar_toolbar_alter(&$items) {

  // Alter the label of the "Local Tasks" link created by the Gin Toolbar for
  // all nodes. Change to "Manage this Page" to make it easier to understand.
  if (\Drupal::service('ys_toolbar.items')->isCurrentRouteNode()) {
    if (!empty($items['admin_toolbar_local_tasks']['tab']['#title'])) {
      $items['admin_toolbar_local_tasks']['tab']['#title'] = 'Toolset';
    }
  }

  // Remove the contextual toggle. This control is confusing to our authors
  // and is not important for our editorial workflow.
  unset($items['contextual']);
}

/**
 * Implements hook_toolbar().
 */
function ys_toolbar_toolbar() {
  return \Drupal::service('ys_toolbar.items')->addItems();
}
