<?php

/**
 * Add template files
 *
 * Implements hook_theme().
 */
function ys_layouts_theme($existing, $type, $theme, $path): array {
  return [
    'ys_event_meta_block' => [
      'variables' => [
        'event_title__heading' => NULL,
        'event_meta__date_start' => NULL,
        'event_meta__date_end' => NULL,
        'event_meta__date_duration' => NULL,
        'event_meta__format' => [],
        'event_meta__cta_primary__href' => NULL,
        'event_meta__cta_primary__content' => NULL,
      ],
    ],
  ];
}

