<?php

/**
 * @file
 * Contains ys_layouts.module functions.
 */

/**
 * Add template files.
 *
 * Implements hook_theme().
 */
function ys_layouts_theme($existing, $type, $theme, $path): array {
  return [
    'ys_event_meta_block' => [
      'variables' => [
        'event_title__heading' => NULL,
        'event_meta__date_start' => NULL,
        'event_meta__date_end' => NULL,
        'event_meta__date_duration' => NULL,
        'event_meta__all_day' => NULL,
        'event_meta__format' => [],
        'event_meta__cta_primary__href' => NULL,
        'event_meta__cta_primary__content' => NULL,
        'calendar_location_text' => NULL,
      ],
    ],
    'ys_page_meta_block' => [
      'variables' => [
        'page_title' => NULL,
        'page_title_display' => 'visible',
      ],
    ],
    'ys_post_meta_block' => [
      'variables' => [
        'label' => NULL,
        'date_formatted' => NULL,
      ],
    ],
    'ys_profile_meta_block' => [
      'variables' => [
        'name' => NULL,
        'position' => NULL,
        'subtitle' => NULL,
        'department' => NULL,
        'media_id' => NULL,
      ],
    ],
  ];
}
