<?php

/**
 * @file
 * Contains ys_layouts.module functions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Add template files.
 *
 * Implements hook_theme().
 */
function ys_layouts_theme($existing, $type, $theme, $path): array {
  return [
    'ys_event_meta_block' => [
      'variables' => [
        'event_title__heading' => NULL,
        'event_meta__date_start' => NULL,
        'event_meta__date_end' => NULL,
        'event_meta__date_duration' => NULL,
        'event_meta__all_day' => NULL,
        'event_meta__format' => [],
        'event_meta__cta_primary__href' => NULL,
        'event_meta__cta_primary__content' => NULL,
        'calendar_location_text' => NULL,
      ],
    ],
    'ys_page_meta_block' => [
      'variables' => [
        'page_title' => NULL,
        'page_title_display' => 'visible',
      ],
    ],
    'ys_post_meta_block' => [
      'variables' => [
        'label' => NULL,
        'author' => NULL,
        'date_formatted' => NULL,
      ],
    ],
    'ys_profile_meta_block' => [
      'variables' => [
        'profile_meta__heading' => NULL,
        'profile_meta__title_line' => NULL,
        'profile_meta__subtitle_line' => NULL,
        'profile_meta__department' => NULL,
        'media_id' => NULL,
      ],
    ],
    'ys_profile_contact_block' => [
      'variables' => [
        'email' => NULL,
        'phone' => NULL,
        'address' => [],
      ],
    ],
  ];
}

/**
 * Allows global blocks to use the same template as inline blocks.
 *
 * Implements hook_theme_suggestions_block().
 */
function ys_layouts_theme_suggestions_block($variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    return [
      'block__inline_block__' . $variables['elements']['content']['#block_content']->bundle(),
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function ys_layouts_form_alter(&$form, $form_state, $form_id) {

  /* Add messaging with link to edit global block and destination back to
  layout builder. Or set reusable based on checkbox.
   */
  if ($form_id == 'layout_builder_update_block' || $form_id == 'layout_builder_add_block') {
    $reusableNote = '<p>Note: This is a global block. Any changes made to a global block will be reflected anywhere it is used.</p>';

    // Reusable block form - block_form is not set on global blocks.
    if (!isset($form['settings']['block_form'])) {
      // We need the global block uuid to look up the block id.
      $blockUUID = explode(":", $form_state->getBuildInfo()['callback_object']->getCurrentComponent()->get('configuration')['id']);
      $blocks = \Drupal::entityTypeManager()->getStorage('block_content')->loadByProperties([
        'uuid' => $blockUUID[1],
      ]);
      $blockId = array_key_first($blocks);

      // We need the current path to extract the node id.
      $current_path = \Drupal::service('path.current')->getPath();
      preg_match('/node\.(\d+)/', $current_path, $matches);

      // Compiled global block message.
      $form['settings']['global_info'] = [
        '#markup' => "{$reusableNote} <a class='glb-button glb-button--primary' href='/admin/content/block/{$blockId}?destination=/node/{$matches[1]}/layout'>Edit Global Block</a>",
      ];
    }
    else {
      // Non-global blocks form. Add ability to turn into reusable block.
      if (!$form['settings']['block_form']['#block']->isReusable()) {
        $form['settings']['reusable'] = [
          '#type' => 'checkbox',
          '#title' => t('Make this block reusable'),
        ];

        // Change order of submit handler to save reusable afterwords.
        array_unshift($form['#submit'], '_ys_layouts_set_reusable');
      }
      else {
        $form['settings']['global_info'] = [
          '#markup' => $reusableNote,
        ];
      }
    }
  }
}

/**
 * Sets reusable block if checkbox is checked.
 */
function _ys_layouts_set_reusable(&$form, FormStateInterface $form_state) {
  if ($form_state->getValue(['settings', 'reusable'])) {
    /** @var \Drupal\block_content\BlockContentInterface $block_content */
    $block_content = $form['settings']['block_form']['#block'];
    $block_content->setReusable();
    $block_content->save();
  }
}

/**
 * Implements hook_preprocess_block().
 */
function ys_layouts_preprocess_block(&$variables) {
  // Sets variable if block is reusable for layout builder preview for styling.
  if ($variables['in_preview'] && isset($variables['content']['#block_content'])) {
    if ($variables['content']['#block_content']->isReusable()) {
      $variables['is_reusable'] = TRUE;
    }
  }
}
