<?php

/**
 * @file
 * Contains ys_core.module functions.
 */

/**
 * Add template file for social links.
 *
 * Implements hook_theme().
 */
function ys_core_theme($existing, $type, $theme, $path): array {
  return [
    'ys_social_links' => [
      'variables' => [
        'social_links' => [],
      ],
    ],
  ];
}

/**
 * Add twig variable to breadcrumb to show only if greater than 2 levels deep.
 *
 * Implements hook_preprocess_breadcrumb().
 */
function ys_core_preprocess_breadcrumb(&$variables) {
  $breadCrumbLevel = count($variables['breadcrumb']);
  $variables['show_breadcrumb'] = ($breadCrumbLevel > 2) ? true : false;
}
