RUN if [ -f /etc/ImageMagick-6/policy.xml ]; then \
      sed -i 's#<policy domain="coder" rights="none" pattern="PDF" />#<policy domain="coder" rights="read|write" pattern="PDF" />#g' /etc/ImageMagick-6/policy.xml; \
    fi
