<?php

/**
 * @file
 * Contains ys_ai_chatbot.module functions.
 */

/**
 * Add template files for custom blocks.
 *
 * Implements hook_theme().
 */
function ys_ai_chatbot_theme($existing, $type, $theme, $path): array {
  return [
    'ys_ai_chatbot_block' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function ys_ai_chatbot_library_info_alter(&$libraries, $extension) {
  // Gets dynamically generated JS and CSS from Create React App.
  // @see https://www.drupal.org/forum/support/module-development-and-code-questions/2020-09-18/custom-module-how-to-include-jscss

  if ($extension != 'ys_ai_chatbot') {
      return;
    }
  if (!is_dir('libraries/yale_ai_react_chat/build')) {
    return;
  }

  $path = 'libraries/yale_ai_react_chat/build/static/js';
  $js_filenames = glob($path . '/main\.*.js');
  $js_file_path = '/' . $js_filenames[0];
  $libraries['react_app']['js'][$js_file_path] = [];

  $path = 'libraries/yale_ai_react_chat/build/static/css';
  $css_filenames = glob($path . '/main\.*.css');
  $css_file_path = '/' . $css_filenames[0];
  $libraries['react_app']['css']['theme'][$css_file_path] = [];
}
