site_uuid: 3be7d457-cc13-4e03-bde2-d004a9e0f46e
uuid: 0b76ce3c-3bae-41df-a671-730ad832b6a5
entity_type: node
bundle: post
base_fields:
  title: 'Your New Blog'
  status: true
  langcode: en
  created: '1705674722'
  author: admin@example.com
  url: /posts/2024-01-13-your-new-blog
  revision_log_message: null
  revision_uid: '1'
custom_fields:
  field_author:
    -
      value: Someone
  field_category: null
  field_login_required:
    -
      value: '0'
  field_metatags: null
  field_publish_date:
    -
      value: '2024-01-13'
  field_tags: null
  field_teaser_media:
    -
      uuid: cae04706-21ac-41aa-9dd6-8f2e509ddb3a
      entity_type: media
      bundle: image
      base_fields:
        name: yale-brick-in-wall-detail.jpg
        created: '1691755627'
        status: true
        langcode: en
      custom_fields:
        field_media_image:
          -
            uri: 'public://2023-08/yale-brick-in-wall-detail.jpg'
            url: 'https://yalesites-platform.lndo.site/sites/default/files/2023-08/yale-brick-in-wall-detail.jpg'
            alt: 'brick wall with YALE carved into one of the bricks'
            title: ''
  field_teaser_text:
    -
      value: '<p>Change this please.</p>'
      format: heading_html
  field_teaser_title:
    -
      value: 'A blog'
  layout_builder__layout: null

