site_uuid: 3be7d457-cc13-4e03-bde2-d004a9e0f46e
uuid: 96430bf9-1d0c-47bb-aead-d719c2b46b50
entity_type: node
bundle: profile
base_fields:
  title: 'Keynote speaker profile'
  status: true
  langcode: en
  created: '1713804301'
  author: sebastianna@fourkitchens.com
  url: /profile/keynote-speaker-profile
  revision_log_message: null
  revision_uid: '2'
custom_fields:
  field_address: null
  field_affiliation: null
  field_department: null
  field_email: null
  field_external_source: null
  field_first_name: null
  field_honorific_prefix: null
  field_last_name: null
  field_login_required:
    - value: '0'
  field_media:
    - uuid: 92f71058-0a49-427f-b664-c4e073129abd
      entity_type: media
      bundle: image
      base_fields:
        name: Stone-Carving-Sheffield-Sterling-Strathcona-Hall-01.jpg
        created: '1713973028'
        status: true
        langcode: en
      custom_fields:
        field_media_image:
          - uri: 'public://2024-04/Stone-Carving-Sheffield-Sterling-Strathcona-Hall-01.jpg'
            url: 'https://dev-yalesites-sebastianna.pantheonsite.io/sites/default/files/2024-04/Stone-Carving-Sheffield-Sterling-Strathcona-Hall-01.jpg'
            alt: "stone carving of a grinning gargoyle's face on building exterior"
            title: ''
  field_metatags: null
  field_position:
    - value: 'Professional Title'
  field_subtitle: null
  field_tags:
    - uuid: f0257bf6-13f6-4d15-8afa-9d25202ff1a2
      entity_type: taxonomy_term
      bundle: tags
      base_fields:
        name: conference
        weight: 0
        langcode: en
        description: null
        parent: 0
      custom_fields: {}
    - uuid: 835bc428-dc8f-42a8-a457-aba9148153d9
      entity_type: taxonomy_term
      bundle: tags
      base_fields:
        name: featured
        weight: 0
        langcode: en
        description: null
        parent: 0
      custom_fields: {}
    - uuid: e726a484-6dcd-4751-a080-3d5529ebb860
      entity_type: taxonomy_term
      bundle: tags
      base_fields:
        name: 'starter kit'
        weight: 0
        langcode: en
        description: null
        parent: 0
      custom_fields: {}
  field_teaser_media: null
  field_teaser_text: null
  field_teaser_title: null
  field_telephone: null
  layout_builder__layout:
    sections: TzoyOToiRHJ1cGFsXGxheW91dF9idWlsZGVyXFNlY3Rpb24iOjQ6e3M6MTE6IgAqAGxheW91dElkIjtzOjE2OiJ5c19sYXlvdXRfYmFubmVyIjtzOjE3OiIAKgBsYXlvdXRTZXR0aW5ncyI7YToyOntzOjU6ImxhYmVsIjtzOjE0OiJCYW5uZXIgU2VjdGlvbiI7czoxNToiY29udGV4dF9tYXBwaW5nIjthOjA6e319czoxMzoiACoAY29tcG9uZW50cyI7YToxOntzOjM2OiIwM2JhZWZjNS0yOTRlLTQ4MGMtODVhNi1iMzVlYzJjNWZmMmEiO086Mzg6IkRydXBhbFxsYXlvdXRfYnVpbGRlclxTZWN0aW9uQ29tcG9uZW50Ijo1OntzOjc6IgAqAHV1aWQiO3M6MzY6IjAzYmFlZmM1LTI5NGUtNDgwYy04NWE2LWIzNWVjMmM1ZmYyYSI7czo5OiIAKgByZWdpb24iO3M6NzoiY29udGVudCI7czoxNjoiACoAY29uZmlndXJhdGlvbiI7YTo1OntzOjI6ImlkIjtzOjE4OiJwcm9maWxlX21ldGFfYmxvY2siO3M6NToibGFiZWwiO3M6MTg6IlByb2ZpbGUgTWV0YSBCbG9jayI7czoxMzoibGFiZWxfZGlzcGxheSI7czowOiIiO3M6ODoicHJvdmlkZXIiO3M6MTA6InlzX2xheW91dHMiO3M6MTU6ImNvbnRleHRfbWFwcGluZyI7YTowOnt9fXM6OToiACoAd2VpZ2h0IjtpOjA7czoxMzoiACoAYWRkaXRpb25hbCI7YTowOnt9fX1zOjIxOiIAKgB0aGlyZFBhcnR5U2V0dGluZ3MiO2E6MTp7czoxOToibGF5b3V0X2J1aWxkZXJfbG9jayI7YToxOntzOjQ6ImxvY2siO2E6Nzp7aToxO2k6MTtpOjI7aToyO2k6MztpOjM7aTo0O2k6NDtpOjU7aTo1O2k6NjtpOjY7aTo4O2k6ODt9fX19fE86Mjk6IkRydXBhbFxsYXlvdXRfYnVpbGRlclxTZWN0aW9uIjo0OntzOjExOiIAKgBsYXlvdXRJZCI7czoxMzoibGF5b3V0X29uZWNvbCI7czoxNzoiACoAbGF5b3V0U2V0dGluZ3MiO2E6Mjp7czo1OiJsYWJlbCI7czo3OiJvbmUgY29sIjtzOjE1OiJjb250ZXh0X21hcHBpbmciO2E6MDp7fX1zOjEzOiIAKgBjb21wb25lbnRzIjthOjU6e3M6MzY6ImEwMzRlZjJjLWI3YzMtNDhkYy1iMGZiLWRmNDcyYzQ3ZTZhYSI7TzozODoiRHJ1cGFsXGxheW91dF9idWlsZGVyXFNlY3Rpb25Db21wb25lbnQiOjU6e3M6NzoiACoAdXVpZCI7czozNjoiYTAzNGVmMmMtYjdjMy00OGRjLWIwZmItZGY0NzJjNDdlNmFhIjtzOjk6IgAqAHJlZ2lvbiI7czo3OiJjb250ZW50IjtzOjE2OiIAKgBjb25maWd1cmF0aW9uIjthOjg6e3M6MjoiaWQiO3M6MTc6ImlubGluZV9ibG9jazp0ZXh0IjtzOjU6ImxhYmVsIjtzOjMxOiJLZXlub3RlIFByb2ZpbGUgRW1waGFzaXplZCBUZXh0IjtzOjEzOiJsYWJlbF9kaXNwbGF5IjtiOjA7czo4OiJwcm92aWRlciI7czoxNDoibGF5b3V0X2J1aWxkZXIiO3M6OToidmlld19tb2RlIjtzOjQ6ImZ1bGwiO3M6MTc6ImJsb2NrX3JldmlzaW9uX2lkIjtzOjQ6IjEzNzMiO3M6MTY6ImJsb2NrX3NlcmlhbGl6ZWQiO047czoxNToiY29udGV4dF9tYXBwaW5nIjthOjA6e319czo5OiIAKgB3ZWlnaHQiO3M6MToiMCI7czoxMzoiACoAYWRkaXRpb25hbCI7YTowOnt9fXM6MzY6IjRmZTllYWZiLTU0ZTItNGM3Zi1hZDNjLWNhNTkxN2ZjZmUyNCI7TzozODoiRHJ1cGFsXGxheW91dF9idWlsZGVyXFNlY3Rpb25Db21wb25lbnQiOjU6e3M6NzoiACoAdXVpZCI7czozNjoiNGZlOWVhZmItNTRlMi00YzdmLWFkM2MtY2E1OTE3ZmNmZTI0IjtzOjk6IgAqAHJlZ2lvbiI7czo3OiJjb250ZW50IjtzOjE2OiIAKgBjb25maWd1cmF0aW9uIjthOjg6e3M6MjoiaWQiO3M6MTc6ImlubGluZV9ibG9jazp0ZXh0IjtzOjU6ImxhYmVsIjtzOjIwOiJLZXlub3RlIFByb2ZpbGUgVGV4dCI7czoxMzoibGFiZWxfZGlzcGxheSI7YjowO3M6ODoicHJvdmlkZXIiO3M6MTQ6ImxheW91dF9idWlsZGVyIjtzOjk6InZpZXdfbW9kZSI7czo0OiJmdWxsIjtzOjE3OiJibG9ja19yZXZpc2lvbl9pZCI7czo0OiIxMzc0IjtzOjE2OiJibG9ja19zZXJpYWxpemVkIjtOO3M6MTU6ImNvbnRleHRfbWFwcGluZyI7YTowOnt9fXM6OToiACoAd2VpZ2h0IjtpOjE7czoxMzoiACoAYWRkaXRpb25hbCI7YTowOnt9fXM6MzY6IjE5NWJmNDhlLWYzZWMtNGQ2Ni1hMWFjLWNiZjNhYmU1NzNiYiI7TzozODoiRHJ1cGFsXGxheW91dF9idWlsZGVyXFNlY3Rpb25Db21wb25lbnQiOjU6e3M6NzoiACoAdXVpZCI7czozNjoiMTk1YmY0OGUtZjNlYy00ZDY2LWExYWMtY2JmM2FiZTU3M2JiIjtzOjk6IgAqAHJlZ2lvbiI7czo3OiJjb250ZW50IjtzOjE2OiIAKgBjb25maWd1cmF0aW9uIjthOjg6e3M6MjoiaWQiO3M6MTg6ImlubGluZV9ibG9jazp2aWRlbyI7czo1OiJsYWJlbCI7czozNjoiQ29uZmVyZW5jZSBTdGFydGVyIEtpdCBQcm9maWxlIFZpZGVvIjtzOjEzOiJsYWJlbF9kaXNwbGF5IjtiOjA7czo4OiJwcm92aWRlciI7czoxNDoibGF5b3V0X2J1aWxkZXIiO3M6OToidmlld19tb2RlIjtzOjQ6ImZ1bGwiO3M6MTc6ImJsb2NrX3JldmlzaW9uX2lkIjtzOjQ6IjEzNzUiO3M6MTY6ImJsb2NrX3NlcmlhbGl6ZWQiO047czoxNToiY29udGV4dF9tYXBwaW5nIjthOjA6e319czo5OiIAKgB3ZWlnaHQiO2k6MztzOjEzOiIAKgBhZGRpdGlvbmFsIjthOjA6e319czozNjoiMGM2MGIwZTUtOTg3Zi00OTAyLWE0NjktYmZjMjI5OTA0OTczIjtPOjM4OiJEcnVwYWxcbGF5b3V0X2J1aWxkZXJcU2VjdGlvbkNvbXBvbmVudCI6NTp7czo3OiIAKgB1dWlkIjtzOjM2OiIwYzYwYjBlNS05ODdmLTQ5MDItYTQ2OS1iZmMyMjk5MDQ5NzMiO3M6OToiACoAcmVnaW9uIjtzOjc6ImNvbnRlbnQiO3M6MTY6IgAqAGNvbmZpZ3VyYXRpb24iO2E6ODp7czoyOiJpZCI7czoyMDoiaW5saW5lX2Jsb2NrOmNhbGxvdXQiO3M6NToibGFiZWwiO3M6MzY6IkNvbmZlcmVuY2UgU3RhcnRlciBLaXQgUHJvZmlsZSBWaWRlbyI7czoxMzoibGFiZWxfZGlzcGxheSI7YjowO3M6ODoicHJvdmlkZXIiO3M6MTQ6ImxheW91dF9idWlsZGVyIjtzOjk6InZpZXdfbW9kZSI7czo0OiJmdWxsIjtzOjE3OiJibG9ja19yZXZpc2lvbl9pZCI7czo0OiIxMzc2IjtzOjE2OiJibG9ja19zZXJpYWxpemVkIjtOO3M6MTU6ImNvbnRleHRfbWFwcGluZyI7YTowOnt9fXM6OToiACoAd2VpZ2h0IjtpOjQ7czoxMzoiACoAYWRkaXRpb25hbCI7YTowOnt9fXM6MzY6ImUzNDgzYTM5LWRhOTMtNGZiYi04NjE1LTBmOTk1NTBhNmJlNCI7TzozODoiRHJ1cGFsXGxheW91dF9idWlsZGVyXFNlY3Rpb25Db21wb25lbnQiOjU6e3M6NzoiACoAdXVpZCI7czozNjoiZTM0ODNhMzktZGE5My00ZmJiLTg2MTUtMGY5OTU1MGE2YmU0IjtzOjk6IgAqAHJlZ2lvbiI7czo3OiJjb250ZW50IjtzOjE2OiIAKgBjb25maWd1cmF0aW9uIjthOjg6e3M6MjoiaWQiO3M6MjQ6ImlubGluZV9ibG9jazpidXR0b25fbGluayI7czo1OiJsYWJlbCI7czo0MjoiQ29uZmVyZW5jZSBTdGFydGVyIEtpdCBQcm9maWxlIEJ1dHRvbiBMaW5rIjtzOjEzOiJsYWJlbF9kaXNwbGF5IjtiOjA7czo4OiJwcm92aWRlciI7czoxNDoibGF5b3V0X2J1aWxkZXIiO3M6OToidmlld19tb2RlIjtzOjQ6ImZ1bGwiO3M6MTc6ImJsb2NrX3JldmlzaW9uX2lkIjtzOjQ6IjEzNzciO3M6MTY6ImJsb2NrX3NlcmlhbGl6ZWQiO047czoxNToiY29udGV4dF9tYXBwaW5nIjthOjA6e319czo5OiIAKgB3ZWlnaHQiO2k6MjtzOjEzOiIAKgBhZGRpdGlvbmFsIjthOjA6e319fXM6MjE6IgAqAHRoaXJkUGFydHlTZXR0aW5ncyI7YTowOnt9fQ==
    blocks:
      - uuid: 24359e04-aade-4d61-91e0-a6a3256fe395
        entity_type: block_content
        bundle: text
        base_fields:
          info: 'Keynote Profile Emphasized Text'
          reusable: false
          langcode: en
          block_revision_id: '1373'
          enforce_new_revision: true
        custom_fields:
          field_instructions:
            - markup: null
          field_style_variation:
            - value: emphasized
          field_text:
            - value: '<p>Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Diam ut venenatis tellus in metus vulputate.</p>'
              format: basic_html
      - uuid: 02ad950b-b5fe-4063-9759-3f2406137e88
        entity_type: block_content
        bundle: text
        base_fields:
          info: 'Keynote Profile Text'
          reusable: false
          langcode: en
          block_revision_id: '1374'
          enforce_new_revision: true
        custom_fields:
          field_instructions:
            - markup: null
          field_style_variation:
            - value: default
          field_text:
            - value: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus id interdum velit laoreet. Nunc sed velit dignissim sodales. Nunc lobortis mattis aliquam faucibus purus. Ultrices gravida dictum fusce ut placerat orci. Varius morbi enim nunc faucibus a pellentesque. Risus in hendrerit gravida rutrum quisque non tellus. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Diam ut venenatis tellus in metus vulputate.</p>'
              format: basic_html
      - uuid: 1bdae214-1384-413c-aca7-9aeb2f8b66a7
        entity_type: block_content
        bundle: video
        base_fields:
          info: 'Conference Starter Kit Profile Video'
          reusable: false
          langcode: en
          block_revision_id: '1375'
          enforce_new_revision: true
        custom_fields:
          field_heading:
            - value: 'Video highlight'
              format: heading_html
          field_instructions:
            - markup: null
          field_media:
            - uuid: ba195620-d674-451e-b6c5-55027f603dd1
              entity_type: media
              bundle: video
              base_fields:
                name: 'The Glass Smiths: The family craftsmen behind Yale’s Glass Shop'
                created: '1686322179'
                status: true
                langcode: en
              custom_fields:
                field_media_oembed_video:
                  - value: 'https://youtu.be/C8kcTvNnWPI'
          field_text: null
      - uuid: f610305e-b420-4494-b0e8-36e9598fdd15
        entity_type: block_content
        bundle: callout
        base_fields:
          info: 'Conference Starter Kit Profile Video'
          reusable: false
          langcode: en
          block_revision_id: '1376'
          enforce_new_revision: true
        custom_fields:
          field_callout:
            - uuid: 438ae3d0-1c39-433c-b693-d3a08b86892d
              entity_type: paragraph
              bundle: callout_item
              base_fields:
                status: true
                langcode: en
                created: '1713805942'
                behavior_settings: {}
              custom_fields:
                field_heading:
                  - value: "Don't miss this event"
                    format: heading_html
                field_link:
                  - uri: 'internal:/'
                    title: Register
                    options:
                      href: 'internal:/'
                      data-entity-type: ''
                      data-entity-uuid: ''
                      data-entity-substitution: ''
                field_text:
                  - value: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>'
                    format: heading_html
          field_instructions:
            - markup: null
          field_style_alignment:
            - value: center
          field_style_color:
            - value: one
      - uuid: ed669e51-a5f6-404a-bfc6-226596710426
        entity_type: block_content
        bundle: button_link
        base_fields:
          info: 'Conference Starter Kit Profile Button Link'
          reusable: false
          langcode: en
          block_revision_id: '1377'
          enforce_new_revision: true
        custom_fields:
          field_button_link:
            - uri: 'https://yalesites.yale.edu'
              title: "Speaker's website"
              options:
                href: 'https://yalesites.yale.edu'
                data-entity-type: ''
                data-entity-uuid: ''
                data-entity-substitution: ''
