<?php

/**
 * Implements hook_form_alter.
 */
function ys_mail_form_alter(&$form, &$form_state, $form_id) {
  // Disable the mailchimp_transactional_api_key field from the admin form as
  // the value is set via Drupal\ys_mail\Config\MailConfigOverrides.
  if ($form_id == 'mailchimp_transactional_admin_settings') {
    $form['mailchimp_transactional_api_key']['#attributes']['disabled'] = 'disabled';
  }
}
