<?php

/**
 * @file
 * The ys_mail module.
 */

/**
 * Implements hook_form_alter().
 */
function ys_mail_form_alter(&$form, &$form_state, $form_id) {
  // Disable the mailchimp_transactional_api_key field from the admin form as
  // the value is set via Drupal\ys_mail\Config\MailConfigOverrides.
  if ($form_id == 'mailchimp_transactional_admin_settings') {
    $form['mailchimp_transactional_api_key']['#attributes']['disabled'] = 'disabled';
  }
}

/**
 * Implements hook_mailchimp_transactional_mail_alter().
 */
function ys_mail_mailchimp_transactional_mail_alter(&$mailchimp_transactional_params, $message) {
  // Unset tags to avoid runaway tag creation.
  unset($mailchimp_transactional_params['message']['tags']);

  // Populate custom metadata fields.
  $mailchimp_transactional_params['message']['metadata'] = [
    'site' => $_SERVER['HTTP_HOST'],
    'form_id' => $message['id'],
  ];
}
