<?php

/**
 * @file
 * Primary module hooks for YS Localist module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ys_localist_form_alter(&$form, &$form_state, $form_id) {
  // Disables fields that are imported from Localist.
  $formsToCheck = [
    'node_event_form',
    'node_event_edit_form',
    'node_event_quick_node_clone_form',
  ];

  if (in_array($form_id, $formsToCheck)) {
    $fieldsToDisable = [
      'field_localist_id',
      'field_event_status',
      'field_localist_event_url',
      'field_localist_event_image_url',
      'field_localist_event_image_alt',
      'field_localist_ics_url',
      'field_localist_register_enabled',
    ];
    foreach ($fieldsToDisable as $field) {
      $form[$field]['#disabled'] = TRUE;
    }
  }
}
