ys_unified_search.settings:
  type: config_object
  label: 'Unified Search settings'
  mapping:
    search_options:
      type: sequence
      label: 'Search options'
      sequence:
        type: mapping
        mapping:
          label:
            type: string
            label: 'Search label'
          url:
            type: string
            label: 'Search URL' 