<?php

/**
 * @file
 * The ys_captcha module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ys_captcha_form_recaptcha_admin_settings_alter(&$form, &$form_state, $form_id) {
  // Disable the recaptcha v2 API key fields from the admin form as
  // the value is set via Drupal\ys_captcha\Config\CaptchaV2ConfigOverrides.
  $secrets = \Drupal::service('ys_secrets.manager');
  $secrets->disableField($form['general']['recaptcha_site_key']);
  $secrets->disableField($form['general']['recaptcha_secret_key']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ys_captcha_form_recaptcha_v3_settings_alter(&$form, &$form_state, $form_id) {
  // Disable the recaptcha v3 API key fields from the admin form as
  // the value is set via Drupal\ys_captcha\Config\CaptchaV3ConfigOverrides.
  $secrets = \Drupal::service('ys_secrets.manager');
  $secrets->disableField($form['site_key']);
  $secrets->disableField($form['secret_key']);
}
