<?php

/**
 * @file
 * Primary module hooks for YS ServiceNow module.
 */

/**
 * Implements hook_cron().
 */
function ys_servicenow_cron() {
  $config = \Drupal::config('ys_servicenow.settings');
  if ($config->get('enable_servicenow_sync')) {

    $state = \Drupal::state();

    $next_execution_time = $state->get("servicenow_migrations", 0);
    $current_time = \Drupal::time()->getRequestTime();
    if ($current_time > $next_execution_time) {
      $state->set("servicenow_migrations", $current_time + 3600);
      $servicenowManager = \Drupal::service('ys_servicenow.manager');
      $servicenowManager->runAllMigrations();
    }
  }
}
