<?php

/**
 * @file
 * YaleSites Embed module.
 *
 * This modules functionality for managing embeddable content.
 */

/**
 * Implements hook_theme().
 */
function ys_embed_theme($existing, $type, $theme, $path) {
  return [
    'embed_instructions' => [
      'variables' => [
        'sources' => [],
      ],
    ],
    'embed_wrapper' => [
      'variables' => [
        'embedSource' => [],
        'embedType' => 'unknown',
        'title' => '',
        'url' => '',
        'displayAttributes' => [
          'width' => '100%',
          'height' => '100%',
          'scrolling' => 'no',
          'frameborder' => 'no',
          'isIframe' => TRUE,
          'isForm' => TRUE,
        ],
      ],
    ],
  ];
}
