name: Build, deploy and test

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  static_tests:
    name: Test
    runs-on: ubuntu-26.04
    env:
      YALESITES_BUILD_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check for contrib dependencies in root composer.json
        run: |
          contrib_check=$(jq -r '.require | with_entries(select(.key | test("(drupal\/(?!core).*$)"))) | keys | join(", ")' ./composer.json)
          if [ -n "$contrib_check" ]; then
            echo "::error::$contrib_check found in /composer.json and should be moved to /web/profiles/custom/yalesites_profile/composer.json" && exit 1
          fi
      - name: Check for unpinned dependencies
        run: |
          unpinned_dependencies=$(jq -r '.require | to_entries | map(select(.value | test("\\^|\\~|\\>|\\<")) | "\(.key): \(.value)") | join(", ")' ./web/profiles/custom/yalesites_profile/composer.json)
          if [ -n "$unpinned_dependencies" ]; then
            echo "::error::$unpinned_dependencies found in /web/profiles/custom/yalesites_profile/composer.json. Please switch to pinned versions." && exit 1
          fi

      - name: Run static tests
        run: |
          ./.ci/test/static/run

  deploy_to_pantheon:
    name: Deploy to Pantheon
    runs-on: ubuntu-26.04
    env:
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      MACHINE_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      SITE: ${{ secrets.TERMINUS_SITE }}
    permissions:
      deployments: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
    
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ env.MACHINE_TOKEN }}

      - name: Install Terminus Build Tools Plugin
        run: terminus self:plugin:install terminus-build-tools-plugin

      - name: Build frontend components
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          YALESITES_BUILD_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
        run: |
          ./.ci/build/build_frontend
          git add -A

      - name: Debug
        uses: mxschmitt/action-tmate@v3

      - name: Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.9.2
        id: push-to-pantheon
        with:
          ssh_key: ${{ env.SSH_KEY }}
          machine_token: ${{ env.MACHINE_TOKEN }}
          site: ${{ env.SITE }}
          source_env: "dev"
          delete_old_environments: true
          skip_terminus_install: true

      - name: Wait for Pantheon sync_code workflow to finish
        env:
          TARGET_ENV: ${{ steps.push-to-pantheon.outputs.target_env }}
        run: |
          while true; do
          status=$(terminus workflow:info:status "$SITE.$TARGET_ENV" --field=status 2>/dev/null)
          echo "Current workflow status: $status"
          if [[ "$status" != "running" ]]; then
            echo "Workflow has finished with status: $status"
            break
          fi
          sleep 10
          done

      - name: Wake environment
        env:
          TARGET_ENV: ${{ steps.push-to-pantheon.outputs.target_env }}
        run: terminus -n env:wake "$SITE.$TARGET_ENV" --retry=5 --delay=30

      - name: Run Drush deploy
        env:
          TARGET_ENV: ${{ steps.push-to-pantheon.outputs.target_env }}
        run: terminus -n drush "$SITE.$TARGET_ENV" -- deploy -v -y

      - name: Clear Pantheon cache
        env:
          TARGET_ENV: ${{ steps.push-to-pantheon.outputs.target_env }}
        run: terminus -n env:clear-cache "$SITE.$TARGET_ENV"
