name: Create release pull request
on: workflow_dispatch
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create pull request
      run: ./.ci/github/create_release_pull_request
