name: Create/update release pull request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  create_pull_request:
    if: github.head_ref == 'develop' ||
        github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
      REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create pull request
      run: ./.ci/github/create_release_pull_request
