#!/bin/bash

set -eo pipefail

#
# This script runs static tests which
# can be performed without code execution.
#
# Some example are code sniffing and unit testing
#

# Run composer install to get the vendor directory
composer self-update --2
composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

# Run linting
npm install
npm run test

